[package]
name = "mjml_nif"
version = "1.0.0"
authors = ["Paul Götze"]
edition = "2018"

[lib]
name = "mjml_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = { git = "https://github.com/rusterlium/rustler" }
mrml = "1.0.0"
